version: "3"

services:
  projecty:
    image: projecty-web:latest
    restart: always
    networks:
      - projecty-network
    depends_on:
      - database
    ports:
      - 8080:8080

  database:
   image: mysql:8
   restart: always
   networks:
    - projecty-network
   environment:
    - MYSQL_ROOT_PASSWORD=password
    - MYSQL_DATABASE=projecty
   ports:
     - 3306:33060
   volumes:
     - db-data:/var/lib/mysql
     - ./sql-scripts:/docker-entrypoint-initdb.d

networks:
  projecty-network:

volumes:
  db-data:
